create table if not exists public.monthly_expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 120),
  amount numeric(10, 2) not null check (amount > 0),
  expense_month date not null,
  created_at timestamptz not null default now()
);

create index if not exists monthly_expenses_user_month_created_idx
  on public.monthly_expenses (user_id, expense_month, created_at);

alter table public.monthly_expenses enable row level security;

drop policy if exists "Users read own expenses" on public.monthly_expenses;
create policy "Users read own expenses"
  on public.monthly_expenses for select
  using (user_id = auth.uid());

drop policy if exists "Users add own expenses" on public.monthly_expenses;
create policy "Users add own expenses"
  on public.monthly_expenses for insert
  with check (
    user_id = auth.uid()
    and public.current_app_role() in ('admin', 'member')
  );

drop policy if exists "Users update own expenses" on public.monthly_expenses;
create policy "Users update own expenses"
  on public.monthly_expenses for update
  using (
    user_id = auth.uid()
    and public.current_app_role() in ('admin', 'member')
  )
  with check (user_id = auth.uid());

drop policy if exists "Users delete own expenses" on public.monthly_expenses;
create policy "Users delete own expenses"
  on public.monthly_expenses for delete
  using (
    user_id = auth.uid()
    and public.current_app_role() in ('admin', 'member')
  );
