create table if not exists public.task_timeline_events (
  id bigint generated by default as identity primary key,
  task_log_id bigint not null references public.task_logs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null check (char_length(trim(label)) between 1 and 120),
  created_at timestamptz not null default now()
);

create index if not exists task_timeline_events_task_log_created_idx
  on public.task_timeline_events (task_log_id, created_at);

alter table public.task_timeline_events enable row level security;

create policy "Users can view their own timeline events"
  on public.task_timeline_events for select
  using (auth.uid() = user_id);

create policy "Users can add their own timeline events"
  on public.task_timeline_events for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.task_logs
      where task_logs.id = task_log_id
        and task_logs.user_id = auth.uid()
    )
  );

create policy "Users can update their own timeline events"
  on public.task_timeline_events for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own timeline events"
  on public.task_timeline_events for delete
  using (auth.uid() = user_id);
