create table public.user_invitations (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  role public.app_role not null check (role in ('member', 'viewer')),
  invited_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index user_invitations_active_token_idx
  on public.user_invitations (token_hash, expires_at)
  where used_at is null;

alter table public.user_invitations enable row level security;

-- Tabulai apzināti nav publisku RLS politiku. Tai piekļūst tikai servera API
-- ar service role atslēgu pēc administratora sesijas pārbaudes.
