create table public.user_work_schedule_periods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  valid_from date not null,
  valid_until date,
  regular_start time not null,
  regular_end time not null,
  created_at timestamptz not null default now(),
  constraint work_schedule_period_order check (
    (valid_until is null or valid_until >= valid_from)
    and regular_end > regular_start
  ),
  constraint work_schedule_period_start_unique unique (user_id, valid_from)
);

create index user_work_schedule_periods_lookup_idx
  on public.user_work_schedule_periods (user_id, valid_from, valid_until);

alter table public.user_work_schedule_periods enable row level security;

grant select on table public.user_work_schedule_periods to authenticated;

create policy "Users read accessible work schedule periods"
  on public.user_work_schedule_periods for select
  to authenticated
  using (public.can_read_summary(user_id));
